# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemylecturer', '0002_auto_20180224_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='university',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
