# Generated by Django 2.0.1 on 2018-03-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratemylecturer', '0003_auto_20180228_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturerprofile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='surname',
        ),
    ]
