# Generated by Django 2.0.1 on 2018-03-02 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratemylecturer', '0004_auto_20180302_0109'),
        ('ratemylecturer', '0003_auto_20180227_1153'),
    ]

    operations = [
    ]
