# Generated by Django 2.0.1 on 2018-03-04 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratemylecturer', '0010_auto_20180304_0534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddLecturerProfile',
        ),
    ]
