# Generated by Django 2.0.1 on 2018-03-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratemylecturer', '0014_addlecturerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addlecturerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AddLecturerProfile',
        ),
    ]
