# Generated by Django 2.0.1 on 2018-03-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemylecturer', '0015_auto_20180304_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerprofile',
            name='rating_avr',
            field=models.IntegerField(default=0),
        ),
    ]
