# Generated by Django 2.0.1 on 2018-03-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemylecturer', '0016_lecturerprofile_rating_avr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=-1),
        ),
    ]
