# Generated by Django 2.0.3 on 2018-03-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratemylecturer', '0019_auto_20180323_0429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturerprofile',
            options={'ordering': ['-rating_avr']},
        ),
    ]
