# Generated by Django 2.0.3 on 2018-03-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemylecturer', '0020_auto_20180326_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='picture_url',
            field=models.URLField(default='http://itccthailand.com/wp-content/uploads/2016/07/default-user-icon-profile.png'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='picture_url',
            field=models.URLField(default='http://itccthailand.com/wp-content/uploads/2016/07/default-user-icon-profile.png'),
        ),
    ]
