# Generated by Django 2.0.3 on 2018-03-27 13:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ratemylecturer', '0021_auto_20180326_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[500, 300], upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[500, 300], upload_to='profile_images'),
        ),
    ]
