# Generated by Django 2.0.3 on 2018-03-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemylecturer', '0022_auto_20180327_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturerprofile',
            options={'ordering': ['-rating_avr']},
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='picture_url',
            field=models.URLField(),
        ),
    ]
