# Generated by Django 2.0.3 on 2018-03-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemylecturer', '0023_auto_20180327_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='picture_url',
            field=models.URLField(),
        ),
    ]
