# Generated by Django 2.0.3 on 2018-03-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratemylecturer', '0025_auto_20180328_0247'),
        ('ratemylecturer', '0020_auto_20180327_2144'),
    ]

    operations = [
    ]
