# Generated by Django 2.0.3 on 2018-03-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratemylecturer', '0026_merge_20180328_0708'),
        ('ratemylecturer', '0027_lecturerprofile_uni_slug'),
    ]

    operations = [
    ]
